---
title: "R Notebook"
output: word_document
---

```{r}
library(tidyverse)
library(readr)

#create a dataframe specifying which years were presidential and midterm
president_years <- data.frame(type = "presidential", 
                              year = seq(1980, 2016, 4))

midterm_years <- data.frame(type = "midterm", 
                            year = seq(1982, 2014, 4))

elections <- rbind(president_years, 
                   midterm_years)

#get voter turnout data (from tidytuesday)
turnout <- read_csv("data/voter_turnout.csv",
                    col_types = cols(X1 = col_skip(), 
                    alphanumeric_state_code = col_skip(),
                    icpsr_state_code = col_skip()),
                    na = "NA") %>%
      left_join(elections, by = "year")

turnout
```


```{r Map Data, message=FALSE, warning=FALSE}
library(ggplot2)
library(maps)
library(viridis)

#practice making a map.  Use just 2008 data to have one simple number per state.
just2008 <- turnout %>%
      filter(year == 2008) %>%
      mutate(votes_1K = votes/1000) %>%
      select(state, votes_1K)

#get usa coordinates, and combine with our 2008 election table
m.usa <- map_data("state") %>%
      mutate(state = str_to_title(region, locale = "en")) %>%
      select(-region, -subregion) %>%
      left_join(just2008)
      

#plot!
ggplot(m.usa, aes(x = long,
                  y = lat,
                  group = group,
                  fill = votes_1K)) +
      geom_polygon(color = "grey50", size = 0.2) +
#always include this to give the earth the right proportions
      coord_fixed(1.3) +
      scale_fill_gradient(low = "white", high = "red", na.value = "grey70") +
#try these fill gradients instead of the above one (add a # to add/remove comment) 
      #scale_fill_distiller(palette = "YlOrRd", direction = 1) +
      #scale_fill_distiller(palette = "Spectral", direction = 1) +
      labs(title = "Number of votes cast by state", 
             subtitle = "2008 Presidential Election", x = "", y = "") +
      theme(axis.ticks = element_blank(), 
            axis.text = element_blank())


```



